services:
  nginx:
    container_name: nginx
    image: nginx:custom
    build: requirements/nginx
    networks:
      - inception-network
    volumes:
      - www:/var/www/html
    ports:
      - "443:443"
      # - "80:80"
    depends_on: 
      - wordpress

  mariadb:
    container_name: mariadb
    image: mariadb:custom
    build: requirements/mariadb
    networks:
      - inception-network
    volumes:
      - database:/var/lib/mysql
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${DB_USER} -p${DB_USER_PASS}"]
      interval: 3s
      start_period: 3s

  wordpress:
    container_name: wordpress
    image: wordpress:custom
    build: requirements/wordpress
    networks:
      - inception-network
    volumes: 
      - www:/var/www/html
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  inception-network:
    driver: bridge


volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: /Users/leosohler/data/www
      o: bind

  database:
    driver: local
    driver_opts:
      type: none
      device: /Users/leosohler/data/database
      o: bind
