services:
  nginx:
    container_name: nginx
    image: nginx:custom
    build: requirements/nginx
    networks:
      - inception-network
    volumes:
      - www:/var/www/html
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    image: mariadb:custom
    build: requirements/mariadb
    networks:
      - inception-network
    volumes:
      - database:/var/lib/mysql
    env_file: .env


networks:
  inception-network:
    name: inception-network


volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: /home/lsohler/data/www
      o: bind

  database:
    driver: local
    driver_opts:
      type: none
      device: /home/lsohler/data/database
      o: bind
